# Generated by Django 4.2.1 on 2023-05-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagenCuatro',
            field=models.ImageField(null=True, upload_to='CarpetaDestino', verbose_name='Cuarta imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenDos',
            field=models.ImageField(null=True, upload_to='CarpetaDestino', verbose_name='Segunda imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenTres',
            field=models.ImageField(null=True, upload_to='CarpetaDestino', verbose_name='Tercera imagen'),
        ),
    ]
