# Generated by Django 4.2.1 on 2023-05-30 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_imagencuatro_alter_producto_imagendos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipo', models.CharField(max_length=25, verbose_name='Nombre del tipo de producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tipoNombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipoproducto', verbose_name='La llave del tipo de producto'),
        ),
    ]
