# Generated by Django 4.2.1 on 2023-05-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tipoproducto_producto_tiponombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombreProducto',
            field=models.CharField(max_length=400, verbose_name='El nombre asociado al producto'),
        ),
    ]
