# Generated by Django 4.0.4 on 2023-05-31 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_producto_nombreproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagenCuatro',
            field=models.ImageField(blank=True, null=True, upload_to='CarpetaDestino', verbose_name='Cuarta imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenDos',
            field=models.ImageField(blank=True, null=True, upload_to='CarpetaDestino', verbose_name='Segunda imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenTres',
            field=models.ImageField(blank=True, null=True, upload_to='CarpetaDestino', verbose_name='Tercera imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipoNombre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipoproducto', verbose_name='La llave del tipo de producto'),
        ),
    ]
