# Generated by Django 4.0.4 on 2023-06-29 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='payment_id',
            new_name='payment_transaction',
        ),
    ]
