# Generated by Django 4.0.4 on 2023-06-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_payment_id_usuario_payment_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='payment_transaction',
            field=models.CharField(blank=True, default='valor-manual', max_length=100, null=True),
        ),
    ]
